### PR TITLE
Fix tests and PluginTestCase

### PR DESCRIPTION
**Pull request by mjauvin**

### CODE REVIEW

**Comment by mjauvin** [comment]
What am I misssing here? The tests run fine locally, and that BuilderPluginTestCase class DOES exist.

**Comment by bennothommo** [comment]
@mjauvin what's this intending to fix? The test cases are passing in the `main` branch as far as I can tell?

**Comment by LukeTowers** [comment]
I'm fine with that @bennothommo

**Comment by mjauvin** [comment]
Should we close this, then @bennothommo ?

**Pull request closed without merging**
